### ISSUE TITLE
Chinese is no supported

### ISSUE THREAD

**Issue by kellenwang1017** [gudatr/godot-ai-rpg#2]
I checked the code and realize that all Chinese characters are filtered out for TTS processing, this could be an issue.
I wanna go for LLAMA 3 for better result, is current version supportive to that?

**Comment by gudrob** [comment]
Hey @kellenwang1017,

the project should work out of the box with a 3 or 3.1 model that uses the ChatML format.

EDIT: Sorry, I wrote Instruct earlier but that was because I confused this project with another one.

Since the original piper was effectively licensed GPL V3 (falsely claimed MIT by the author) because it tightly integrated espeak-ng, I demeed it unusable for commercial applications. This project therefore uses a version of piper that uses an english only 600k+ words ipa dictionary and "guesses" words it does not know bases on that: https://github.com/gudatr/piper-without-espeak. Other languages might be added later if I find the time.
I myself will never add Chinese support for it as I have zero Chinese skills but I would be glad if you could add it via a PR.

At a point in time I was using the original piper which should support Chinese and most other languages:
https://github.com/gudatr/godot-ai-rpg/commit/e6f63d3a300d94a13fcba33e05d087fdf4c8098f
This will, however, involve fiddling with bundled python.

At this point, sorry to say but official Chinese support is not within the scope of this project. I will reconsider it, should anyone provide a PR with a commercially usable Chinese phonemizer and Chinese piper-compatible model.
