### ISSUE TITLE
Which commit will work with Windows?

### ISSUE THREAD

**Issue by JimFFM** [gudatr/godot-ai-rpg#6]
> Migrated to llama dylib for Apple Silicon. Windows support is currently broken, use earlier commits for now

I tried one commit before this using **Godot 4.2** [485f87a]

https://github.com/gudatr/godot-ai-rpg/blob/ebb0df5ff725557f692af10dc28505ecb1c17234/scripts/TextToSpeech.cs#L31

### ttslib-win-x64.dl
> where I could download this?
> E 0:00:03:0515   void TextToSpeech.<LoadIPAData>g____PInvoke|9_0(System.Byte*): System.DllNotFoundException: Unable to load DLL 'ttslib-win-x64.dll' or one of its dependencies: The specified module could not be found.

**Comment by gudrob** [comment]
Hey @JimFFM, could you please try out the windows-dlls branch and check if that works for you? Godot 4.3 is what I have tested just now. The backend is using AVX2 and not CUDA or Vulkan for now since I haven't gotten around to writing the auto-detection code yet and vulkan sometimes breaks on "older" hardware; in my case a GTX 1070.
